// ──────────────────────────────────────────────
// HTML One-Sheet Serializer — ResolvedPalette → Self-contained HTML page
// ──────────────────────────────────────────────

import { relativeLuminance } from '../color-utils';
import type { ResolvedPalette } from '../types';

export interface HtmlMeta {
  name: string;
  version: number;
}

const ACCENT_NAMES = ['red', 'green', 'yellow', 'blue', 'purple', 'aqua', 'orange'] as const;
const ACCENT_TIERS = ['bright', 'neutral', 'faded', 'deep'] as const;

function isLight(hex: string): boolean {
  return relativeLuminance(hex) > 0.179;
}

/** Compact swatch: just a div with background + a class for text color */
function sw(hex: string, label: string, lt: string, dt: string, cls = 's'): string {
  const c = isLight(hex) ? 'dk' : 'lt';
  return `<div class="${cls}" style="background:${hex};color:${c === 'dk' ? dt : lt}"><b>${hex}</b>${label}</div>`;
}

function paletteSection(p: ResolvedPalette, mode: string): string {
  const lt = p.fg0, dt = p.bg0;
  const bg = [['bg0_hard',p.bg0_hard],['bg0',p.bg0],['bg0_soft',p.bg0_soft],['bg1',p.bg1],['bg2',p.bg2],['bg3',p.bg3],['bg4',p.bg4]] as const;
  const fg = [['fg0',p.fg0],['fg1',p.fg1],['fg2',p.fg2],['fg3',p.fg3],['fg4',p.fg4],['gray',p.gray]] as const;

  const bgRow = bg.map(([n,v]) => sw(v, n, lt, dt)).join('');
  const fgRow = fg.map(([n,v]) => sw(v, n, lt, dt)).join('');

  const hdr = ACCENT_NAMES.map(n => `<div class="s ah">${n}</div>`).join('');
  const accentRows = ACCENT_TIERS.map(t =>
    '<div class="r">' + ACCENT_NAMES.map(n => {
      const k = `${t}_${n}` as keyof ResolvedPalette;
      return sw(p[k], `${t}_${n}`, lt, dt, 'sa');
    }).join('') + '</div>'
  ).join('');

  const ansi: [number, keyof ResolvedPalette][] = [
    [0,'bg0'],[1,'neutral_red'],[2,'neutral_green'],[3,'neutral_yellow'],
    [4,'neutral_blue'],[5,'neutral_purple'],[6,'neutral_aqua'],[7,'fg4'],
    [8,'gray'],[9,'bright_red'],[10,'bright_green'],[11,'bright_yellow'],
    [12,'bright_blue'],[13,'bright_purple'],[14,'bright_aqua'],[15,'fg1'],
  ];
  const ansiNorm = ansi.slice(0,8).map(([i,k]) => sw(p[k], `${i}`, lt, dt)).join('');
  const ansiBright = ansi.slice(8).map(([i,k]) => sw(p[k], `${i}`, lt, dt)).join('');

  return `<section class="palette-${mode}">
<h2>${mode[0].toUpperCase()+mode.slice(1)} Mode</h2>
<h3>Background</h3><div class="r">${bgRow}</div>
<h3>Foreground</h3><div class="r">${fgRow}</div>
<h3>Accents</h3><div class="r">${hdr}</div>${accentRows}
<h3>Terminal (ANSI 0–15)</h3><div class="r">${ansiNorm}</div><div class="r">${ansiBright}</div>
</section>`;
}

/**
 * Serialize dark and light resolved palettes into a self-contained HTML one-sheet.
 * Zero JS, both color schemes via @media (prefers-color-scheme), printable, <15KB.
 */
export function serializeHtmlOneSheet(
  darkPalette: ResolvedPalette,
  lightPalette: ResolvedPalette,
  meta: HtmlMeta,
): string {
  const date = new Date().toISOString().slice(0, 10);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${meta.name} — Sunfade Retro Palette v${meta.version}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,sans-serif;padding:16px;max-width:960px;margin:0 auto}
header,footer{text-align:center;padding:12px 0}
footer{margin-top:24px;font-size:11px;opacity:.7}
h1{font-size:22px}h2{margin:12px 0 6px}h3{font-size:13px;margin:8px 0 3px}
.meta{font-size:12px;opacity:.7;margin-top:2px}
.r{display:flex;gap:1px;margin-bottom:1px}
.s,.sa{flex:1;padding:6px 8px;min-height:52px;display:flex;flex-direction:column;justify-content:center;font-size:11px}
.sa{min-height:60px}
.s b,.sa b{font-family:monospace;font-size:12px;display:block}
.ah{text-align:center;font-weight:700;min-height:auto;padding:2px}
@media(prefers-color-scheme: dark){body{background:${darkPalette.bg0};color:${darkPalette.fg1}}.palette-light{display:none}}
@media(prefers-color-scheme: light){body{background:${lightPalette.bg0};color:${lightPalette.fg1}}.palette-dark{display:none}}
@media print{.palette-dark,.palette-light{display:block!important}body{background:#fff;color:#000}}
</style>
</head>
<body>
<header><h1>${meta.name}</h1><div class="meta">v${meta.version} · ${date} · Sunfade Retro</div></header>
${paletteSection(darkPalette, 'dark')}
${paletteSection(lightPalette, 'light')}
<footer>Generated by Sunfade Retro</footer>
</body>
</html>
`;}
