// ──────────────────────────────────────────────
// MUI Serializer — ResolvedPalette → MUI createTheme() TypeScript string
// ──────────────────────────────────────────────

import type { Contrast, Mode, ResolvedPalette } from '../types.js';

/**
 * Get the effective background color based on contrast setting.
 */
function getEffectiveBg(palette: ResolvedPalette, contrast: Contrast): string {
  switch (contrast) {
    case 'hard': return palette.bg0_hard;
    case 'soft': return palette.bg0_soft;
    case 'medium': return palette.bg0;
  }
}

/**
 * Serialize a resolved palette into a complete MUI createTheme() TypeScript file.
 * The output is a self-contained .ts file that can be dropped into any MUI project.
 */
export function serializeMuiTheme(
  palette: ResolvedPalette,
  mode: Mode,
  contrast: Contrast,
): string {
  const bg = getEffectiveBg(palette, contrast);

  return `// Sunfade Retro MUI theme — generated by Sunfade Retro
// Mode: ${mode} | Contrast: ${contrast}

import { createTheme } from '@mui/material/styles';

// Module augmentation for custom palette extensions
declare module '@mui/material/styles' {
  interface PaletteColor {
    darker?: string;
  }
  interface SimplePaletteColorOptions {
    darker?: string;
  }
  interface Palette {
    orange: PaletteColor;
  }
  interface PaletteOptions {
    orange?: SimplePaletteColorOptions;
  }
}

const theme = createTheme({
  palette: {
    mode: '${mode}',
    background: {
      default: '${bg}',
      paper: '${palette.bg1}',
    },
    text: {
      primary: '${palette.fg1}',
      secondary: '${palette.fg2}',
      disabled: '${palette.fg4}',
    },
    primary: {
      light: '${palette.bright_blue}',
      main: '${palette.neutral_blue}',
      dark: '${palette.faded_blue}',
      darker: '${palette.deep_blue}',
    },
    secondary: {
      light: '${palette.bright_purple}',
      main: '${palette.neutral_purple}',
      dark: '${palette.faded_purple}',
      darker: '${palette.deep_purple}',
    },
    error: {
      light: '${palette.bright_red}',
      main: '${palette.neutral_red}',
      dark: '${palette.faded_red}',
      darker: '${palette.deep_red}',
    },
    warning: {
      light: '${palette.bright_yellow}',
      main: '${palette.neutral_yellow}',
      dark: '${palette.faded_yellow}',
      darker: '${palette.deep_yellow}',
    },
    success: {
      light: '${palette.bright_green}',
      main: '${palette.neutral_green}',
      dark: '${palette.faded_green}',
      darker: '${palette.deep_green}',
    },
    info: {
      light: '${palette.bright_aqua}',
      main: '${palette.neutral_aqua}',
      dark: '${palette.faded_aqua}',
      darker: '${palette.deep_aqua}',
    },
    orange: {
      light: '${palette.bright_orange}',
      main: '${palette.neutral_orange}',
      dark: '${palette.faded_orange}',
      darker: '${palette.deep_orange}',
    },
    divider: '${palette.bg2}',
    action: {
      hover: '${palette.fg4}14',
      selected: '${palette.fg4}29',
      disabled: '${palette.fg4}',
      disabledBackground: '${palette.bg2}',
    },
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        body: {
          backgroundColor: '${bg}',
          color: '${palette.fg1}',
        },
      },
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          backgroundColor: '${palette.bg1}',
          borderColor: '${palette.bg2}',
        },
      },
    },
    MuiAppBar: {
      styleOverrides: {
        root: {
          backgroundColor: '${palette.bg0_hard}',
          color: '${palette.fg1}',
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 4,
          textTransform: 'none' as const,
        },
      },
    },
    MuiTableCell: {
      styleOverrides: {
        root: {
          borderBottomColor: '${palette.bg2}',
        },
      },
    },
  },
});

export default theme;
`;
}
